"""Fixture-backed data store.

Stands in for the four systems the specialists would talk to in production: a
FHIR server, a claims ledger, a policy document store, and a telemetry time
series database. Each specialist reaches exactly one of them.

Loaded once and cached. Everything here is generated by `fixtures/generate.py`
from a fixed seed.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Any

_FIXTURES = Path(__file__).resolve().parents[3] / "fixtures"


def _read_json(name: str) -> Any:
    path = _FIXTURES / f"{name}.json"
    if not path.exists():
        raise FileNotFoundError(f"missing fixture {path}; run `python fixtures/generate.py`")
    return json.loads(path.read_text(encoding="utf-8"))


@lru_cache(maxsize=1)
def patients() -> list[dict[str, Any]]:
    return _read_json("patients")


@lru_cache(maxsize=1)
def claims() -> list[dict[str, Any]]:
    return _read_json("claims")


@lru_cache(maxsize=1)
def devices() -> list[dict[str, Any]]:
    return _read_json("devices")


@lru_cache(maxsize=1)
def telemetry() -> list[dict[str, Any]]:
    return _read_json("telemetry")


@lru_cache(maxsize=1)
def codesets() -> dict[str, list[dict[str, str]]]:
    return _read_json("codesets")


@lru_cache(maxsize=1)
def policies() -> list[dict[str, str]]:
    """Policy corpus split into sections, each independently citable."""
    docs: list[dict[str, str]] = []
    for path in sorted((_FIXTURES / "policies").glob("*.md")):
        text = path.read_text(encoding="utf-8")
        title = text.splitlines()[0].lstrip("# ").strip()
        # Split on H2 so a citation points at a section, not a whole document.
        chunks = text.split("\n## ")
        docs.append(
            {
                "doc_id": path.stem,
                "title": title,
                "section": "overview",
                "text": chunks[0].strip(),
            }
        )
        for chunk in chunks[1:]:
            heading, _, body = chunk.partition("\n")
            docs.append(
                {
                    "doc_id": path.stem,
                    "title": title,
                    "section": heading.strip(),
                    "text": body.strip(),
                }
            )
    return docs


def find_patients(key: str) -> list[dict[str, Any]]:
    """Every patient matching an id, MRN, or full name.

    Name is a first-class lookup key because that is how clinicians actually
    ask: "what is Samuel Ferreira taking?", not "what is 12345 taking?".
    Resolving it here is safe - this runs inside the data plane, and the model
    only ever handled the placeholder. The real name arrives because
    `rehydrate_args` restored it on the way into the call.

    It returns a list rather than one patient because ids and MRNs are unique
    but names are not. Two people genuinely can be called Samuel Ferreira, and
    the caller has to decide what to do about that.
    """
    wanted = str(key).strip()
    folded = wanted.casefold()
    return [
        patient
        for patient in patients()
        if patient["patient_id"] == wanted
        or patient["mrn"].casefold() == folded
        or patient["name"].casefold() == folded
    ]


def classify_key(value: str) -> str:
    """Which lookup field a value belongs in, judged by its shape.

    One place decides this, because two callers need the same answer for
    different reasons: `match_patients` uses it to put a misplaced value where
    it belongs, and `fhir._unresolved` uses it to report which field was
    actually searched. When those two disagreed, a name that matched nobody was
    reported as "patient_id must be an identifier, search by name instead" -
    advice to do the thing that had just been done.
    """
    text = str(value).strip()
    if not text:
        return ""
    if text.casefold().startswith("mrn-"):
        return "mrn"
    if text.isdigit():
        return "patient_id"
    return "name"


def is_patient_id(value: str) -> bool:
    """True when `value` has the shape of a patient identifier.

    Shape, not existence: a caller needs to distinguish "you gave me a name
    where an id belongs" from "no such patient", and those warrant different
    answers. Ids are bare digits and MRNs are `MRN-` prefixed; a human name is
    neither, and no amount of retrying will make it one.
    """
    text = str(value).strip()
    return bool(text) and (text.isdigit() or text.casefold().startswith("mrn-"))


def match_patients(
    patient_id: str = "",
    mrn: str = "",
    name: str = "",
    birth_date: str = "",
) -> list[dict[str, Any]]:
    """Matches on whichever fields the caller supplied, most exact first.

    Separate arguments rather than one overloaded key, because an id and a name
    are not the same kind of thing and pretending they are caused two distinct
    failures. A name silently reached a plane that only knows ids and matched
    nothing; and a lookup could not say whether it had been given a bad
    identifier or a name it should have searched on.

    Exactness ordering matters: an id or an MRN is unique, so if one is given it
    decides the answer and a name alongside it is at most a filter. Only a
    name-only lookup can be ambiguous, which is what makes ambiguity something
    the caller can plan for rather than a surprise.

    `birth_date` narrows an ambiguous result, the way FHIR's `Patient/$match`
    resolves identity from a set of demographics rather than one string. It
    never narrows a result that was already unique - supplying a date of birth
    separates two people who share a name; it is not an extra hurdle in front
    of an MRN.
    """
    rows = patients()

    # A planner that puts a name in `patient_id` is corrected rather than
    # refused. Separate arguments tell the model what each field means; they
    # cannot make it comply, and the plan is fixed in one round with no chance
    # to observe a complaint and try again. This plane can resolve a name, so
    # the honest reading of "patient_id=Samuel Ferreira" is a name search - and
    # `Router._normalise` already sets the precedent for repairing output that
    # satisfies the schema but not the intent.
    #
    # A plane that *cannot* resolve names refuses instead; see
    # `telemetry._not_an_identifier`. The difference is capability, not policy.
    supplied = str(patient_id).strip()
    if supplied:
        kind = classify_key(supplied)
        if kind == "mrn":
            mrn, patient_id = mrn or supplied, ""
        elif kind == "name":
            name, patient_id = name or supplied, ""

    if str(patient_id).strip():
        wanted = str(patient_id).strip()
        matches = [p for p in rows if p["patient_id"] == wanted]
    elif str(mrn).strip():
        folded = str(mrn).strip().casefold()
        matches = [p for p in rows if p["mrn"].casefold() == folded]
    elif str(name).strip():
        folded = str(name).strip().casefold()
        matches = [p for p in rows if p["name"].casefold() == folded]
    else:
        return []

    if len(matches) > 1 and str(birth_date).strip():
        wanted_dob = str(birth_date).strip()
        narrowed = [p for p in matches if p["birth_date"] == wanted_dob]
        if narrowed:
            return narrowed
    return matches


def resolve_patients(key: str, birth_date: str = "") -> list[dict[str, Any]]:
    """Legacy single-key resolution, kept for callers that still pass one string.

    Prefer `match_patients`, which knows which kind of thing it was handed.
    """
    matches = find_patients(key)
    if len(matches) > 1 and birth_date.strip():
        wanted = birth_date.strip()
        narrowed = [p for p in matches if p["birth_date"] == wanted]
        if narrowed:
            return narrowed
    return matches


def find_patient(key: str) -> dict[str, Any] | None:
    """The one patient matching `key`, or None if the match is not unique.

    Ambiguity is deliberately indistinguishable from absence here: both mean
    "you may not proceed". Returning the first of several matches would hand
    back the wrong person's chart, which is the worst thing this system could
    do quietly.
    """
    matches = find_patients(key)
    return matches[0] if len(matches) == 1 else None


def reset_cache() -> None:
    for fn in (patients, claims, devices, telemetry, codesets, policies):
        fn.cache_clear()
