"""Fixture-backed data store.

Stands in for the four systems the specialists would talk to in production: a
FHIR server, a claims ledger, a policy document store, and a telemetry time
series database. Each specialist reaches exactly one of them.

Loaded once and cached. Everything here is generated by `fixtures/generate.py`
from a fixed seed.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Any

_FIXTURES = Path(__file__).resolve().parents[3] / "fixtures"


def _read_json(name: str) -> Any:
    path = _FIXTURES / f"{name}.json"
    if not path.exists():
        raise FileNotFoundError(f"missing fixture {path}; run `python fixtures/generate.py`")
    return json.loads(path.read_text(encoding="utf-8"))


@lru_cache(maxsize=1)
def patients() -> list[dict[str, Any]]:
    return _read_json("patients")


@lru_cache(maxsize=1)
def claims() -> list[dict[str, Any]]:
    return _read_json("claims")


@lru_cache(maxsize=1)
def devices() -> list[dict[str, Any]]:
    return _read_json("devices")


@lru_cache(maxsize=1)
def telemetry() -> list[dict[str, Any]]:
    return _read_json("telemetry")


@lru_cache(maxsize=1)
def codesets() -> dict[str, list[dict[str, str]]]:
    return _read_json("codesets")


@lru_cache(maxsize=1)
def policies() -> list[dict[str, str]]:
    """Policy corpus split into sections, each independently citable."""
    docs: list[dict[str, str]] = []
    for path in sorted((_FIXTURES / "policies").glob("*.md")):
        text = path.read_text(encoding="utf-8")
        title = text.splitlines()[0].lstrip("# ").strip()
        # Split on H2 so a citation points at a section, not a whole document.
        chunks = text.split("\n## ")
        docs.append(
            {
                "doc_id": path.stem,
                "title": title,
                "section": "overview",
                "text": chunks[0].strip(),
            }
        )
        for chunk in chunks[1:]:
            heading, _, body = chunk.partition("\n")
            docs.append(
                {
                    "doc_id": path.stem,
                    "title": title,
                    "section": heading.strip(),
                    "text": body.strip(),
                }
            )
    return docs


def find_patient(patient_id: str) -> dict[str, Any] | None:
    wanted = str(patient_id).strip()
    for patient in patients():
        if patient["patient_id"] == wanted or patient["mrn"].lower() == wanted.lower():
            return patient
    return None


def reset_cache() -> None:
    for fn in (patients, claims, devices, telemetry, codesets, policies):
        fn.cache_clear()
