"""Cross-plane reconciliation: the comparison no single specialist can make.

Every specialist owns exactly one data source and answers only from it. That
constraint is what keeps routing unambiguous and the trust boundary honest, and
it is not negotiable. But it means a question whose answer *spans* two data
planes has no owner.

Observed live. Asked "claim CLM-8849 for patient 12345 was denied, check their
diagnosis history and tell me whether the billed code matches", Clinical
retrieved the problem list and reported - correctly - that it could not see the
claim. Revenue Cycle retrieved the claim and reported - correctly - that it had
no diagnosis history. Both halves of the answer had been fetched. The
synthesiser, correctly forbidden from adding facts of its own, composed two
accurate refusals into "cannot determine".

## The shape of the fix

This module runs after fan-in, above the data planes. It holds no tools and
cannot retrieve anything: it reads the tool results the specialists already
legitimately fetched and computes a relation between them. Clinical still
cannot call `claim_lookup`; Revenue Cycle still cannot read a chart. Nothing
new is retrieved, and the join is not performed by a language model.

That last clause is the design. `Finding.statement` is a format string filled
from tool output, so the sentence a reader sees about whether two codes match
is deterministic - same claim, same problem list, same words, every run. The
model's remaining job is to explain a result it did not compute.

This is how claim scrubbers actually work. Medical-necessity and bundling edits
are table lookups that cite a rule and an effective date, because the result has
to survive a payer appeal months later. Where those products use models at all,
it is to draft the appeal letter after a deterministic engine has decided.

## Deliberately not a query language

Checks are registered functions, not a general cross-plane query facility. An
unanticipated question still degrades to "cannot determine" - but it degrades
for a reason that can be pointed at, rather than because nothing in the
architecture could ever have joined the evidence. Adding a join is a function,
not a new code path.
"""

from __future__ import annotations

from collections.abc import Callable, Sequence
from typing import Any, Literal

from pydantic import BaseModel, Field

from ..agents.base import SpecialistResult

Verdict = Literal[
    "match",
    "mismatch",
    "applicable",
    "not_applicable",
    "insufficient_evidence",
]


class Finding(BaseModel):
    """One computed comparison, stated in words a person can check.

    `statement` is generated by code and is the only sentence in the final
    answer that no model wrote. `provenance` names the fields compared so a
    reader can verify the claim against the trace without trusting either.
    """

    check: str
    verdict: Verdict
    statement: str
    compared: dict[str, str] = Field(default_factory=dict)
    provenance: str = ""
    # The record this finding is about, used to scope the set against the
    # request. Empty means "not about one particular record", which is never
    # filtered out.
    subject: str = ""


class Evidence:
    """Read-only view over every tool result the specialists retrieved.

    Nothing here reaches a store. `SpecialistResult.tool_calls` already carries
    the redacted tool output and `operator.add` already merges it at fan-in, so
    this is a consumer of existing state rather than a new one.

    Results that errored are dropped on the way in: a check must never treat a
    failure payload as a finding about a record.
    """

    def __init__(self, results: Sequence[SpecialistResult]) -> None:
        self._by_tool: dict[str, list[dict[str, Any]]] = {}
        for result in results:
            for call in result.tool_calls:
                output = call.get("result")
                if not isinstance(output, dict) or "error" in output:
                    continue
                self._by_tool.setdefault(str(call.get("tool")), []).append(output)

    def outputs(self, tool: str) -> list[dict[str, Any]]:
        return self._by_tool.get(tool, [])

    def first(self, tool: str) -> dict[str, Any] | None:
        found = self._by_tool.get(tool)
        return found[0] if found else None

    def has(self, *tools: str) -> bool:
        return all(tool in self._by_tool for tool in tools)


class Check(BaseModel):
    """A registered cross-plane comparison and the evidence it needs."""

    model_config = {"arbitrary_types_allowed": True}

    name: str
    requires: tuple[str, ...]
    run: Callable[[Evidence], list[Finding]]


CHECKS: list[Check] = []


def check(*, name: str, requires: tuple[str, ...]) -> Callable[..., Any]:
    """Register a check.

    Mirrors the `@tool(tools, ...)` decorator in `tools/base.py` so the idiom
    is the one already used in this codebase for "declare a capability and its
    contract in one place".
    """

    def wrap(fn: Callable[[Evidence], list[Finding]]) -> Callable[[Evidence], list[Finding]]:
        CHECKS.append(Check(name=name, requires=requires, run=fn))
        return fn

    return wrap


# -- helpers -----------------------------------------------------------------


def _claims(ev: Evidence) -> list[dict[str, Any]]:
    """Every claim row across all `claim_lookup` results.

    `claim_lookup` returns a list whether it was called with a claim id or a
    patient id, so a question about one patient can legitimately produce
    several findings.
    """
    rows: list[dict[str, Any]] = []
    for output in ev.outputs("claim_lookup"):
        if not output.get("found"):
            continue
        rows.extend(row for row in output.get("claims", []) if isinstance(row, dict))
    return rows


def _patient(ev: Evidence) -> dict[str, Any] | None:
    """The resolved clinical record, if exactly one resolved.

    A `found: false` result includes the ambiguous-match refusal, which is
    precisely the case where comparing would risk using the wrong person's
    chart.
    """
    for output in ev.outputs("fhir_search_patient"):
        if output.get("found"):
            return output
    return None


# -- checks ------------------------------------------------------------------


@check(
    name="billed_diagnosis_matches_problem_list",
    requires=("claim_lookup", "fhir_search_patient"),
)
def billed_diagnosis_matches_problem_list(ev: Evidence) -> list[Finding]:
    """Is the diagnosis billed on the claim recorded on the patient's chart?

    Weaker than what a production scrubber asks, and the difference is worth
    being explicit about: this is set membership against the problem list, not
    medical necessity. "Does this payer cover this CPT for this diagnosis"
    needs LCD/NCD coverage tables the fixtures do not have.
    """
    patient = _patient(ev)
    if patient is None:
        return []

    conditions = [
        str(c["code"])
        for c in patient.get("conditions", [])
        if isinstance(c, dict) and c.get("code")
    ]
    if not conditions:
        # No recorded conditions is not evidence that a billed code is wrong.
        return []

    on_chart = set(conditions)
    listed = ", ".join(sorted(on_chart))
    findings: list[Finding] = []

    for claim in _claims(ev):
        claim_id = str(claim.get("claim_id", "")).strip()
        billed = str(claim.get("icd10_code", "")).strip()
        if not claim_id or not billed:
            continue

        # The join key, checked before anything is compared. Answering for a
        # claim belonging to someone other than the chart we resolved would be
        # a confident statement about two different people at once - the worst
        # output this module could produce.
        if str(claim.get("patient_id", "")).strip() != str(patient.get("patient_id", "")).strip():
            findings.append(
                Finding(
                    check="billed_diagnosis_matches_problem_list",
                    verdict="insufficient_evidence",
                    statement=(
                        f"Claim {claim_id} belongs to a different patient than the "
                        f"clinical record retrieved; no comparison was made."
                    ),
                    provenance=f"{claim_id}.patient_id vs resolved clinical record",
                    subject=claim_id,
                )
            )
            continue

        matched = billed in on_chart
        findings.append(
            Finding(
                check="billed_diagnosis_matches_problem_list",
                verdict="match" if matched else "mismatch",
                statement=(
                    f"Billed diagnosis {billed} on claim {claim_id} is on the "
                    f"patient's active problem list."
                    if matched
                    else (
                        f"Billed diagnosis {billed} on claim {claim_id} is not on the "
                        f"patient's active problem list ({listed})."
                    )
                ),
                compared={"billed_icd10": billed, "problem_list": listed},
                provenance=f"{claim_id}.icd10_code vs resolved patient conditions[]",
                subject=claim_id,
            )
        )

    return findings


@check(name="denial_is_coding_related", requires=("claim_lookup",))
def denial_is_coding_related(ev: Evidence) -> list[Finding]:
    """Would re-billing this claim actually change the outcome?

    Single-plane, and a deliberate exception to the cross-plane framing of this
    module. It belongs here because it is the other half of a useful answer to
    the question that motivated all of this: a denied claim whose diagnosis
    matches the chart is not a coding problem, and saying only "the codes
    match" leaves the reader no better off.

    The classification is attached upstream by `tools/claims.py`, which owns the
    code set. An unclassified code produces no finding rather than a guess.
    """
    findings: list[Finding] = []

    for claim in _claims(ev):
        code = str(claim.get("denial_code") or "").strip()
        if not code or "denial_coding_related" not in claim:
            continue

        claim_id = str(claim.get("claim_id", "")).strip()
        reason = str(claim.get("denial_reason") or "").strip()
        category = str(claim.get("denial_category") or "").replace("_", " ")
        coding = bool(claim["denial_coding_related"])

        findings.append(
            Finding(
                check="denial_is_coding_related",
                verdict="applicable" if coding else "not_applicable",
                statement=(
                    f"Denial {code} on claim {claim_id} ({reason}) is a coding denial; "
                    f"correcting the billed codes is the relevant remedy."
                    if coding
                    else (
                        f"Denial {code} on claim {claim_id} ({reason}) is a {category} "
                        f"denial, not a coding denial; recoding will not resolve it."
                    )
                ),
                compared={"denial_code": code, "category": category},
                provenance=f"{claim_id}.denial_code",
                subject=claim_id,
            )
        )

    return findings


# -- entry point -------------------------------------------------------------


def _in_scope(findings: list[Finding], request: str) -> list[Finding]:
    """Narrow the finding set to the records the request actually named.

    `claim_lookup` returns every claim for a patient, so a question about one
    claim can produce findings about four. That is not a bug in the lookup -
    "are any of this patient's claims miscoded" genuinely wants all of them -
    but handing eight findings to a 4B model for a question about one claim is
    how a correct finding set produces a bad answer.

    Observed: asked about CLM-8972, the model was given findings for all four
    of the patient's claims, mixed them up, and reported both that the billed
    code mismatched and that no billing codes were available.

    So the request sets the scope, the same way it does for identifier
    grounding: if it names records this evidence has findings for, only those
    are reported. If it names none, everything the evidence supports is - which
    is what a question about a patient rather than a claim should return.
    """
    named = [f for f in findings if f.subject and f.subject.casefold() in request.casefold()]
    if not named:
        return findings
    return [f for f in findings if not f.subject or f in named]


def reconcile(results: Sequence[SpecialistResult], request: str = "") -> list[Finding]:
    """Run every check whose required evidence is present.

    `request` is the redacted request, used only to scope the result set. It is
    never read as evidence - nothing here believes anything the request asserts.
    """
    evidence = Evidence(results)
    findings: list[Finding] = []
    for registered in CHECKS:
        if not evidence.has(*registered.requires):
            continue
        findings.extend(registered.run(evidence))
    return _in_scope(findings, request) if request else findings
